import { PrayerRequest } from "../lib/types";

// State for prayer requests
export const data: PrayerRequest[] = [
  // ... (data remains the same)
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah@example.com",
    request:
      "Pray for my mentorship journey as I start a new career path. I feel overwhelmed with decisions about my future and need divine guidance. My mentor has been very supportive but I need spiritual strength to navigate this transition.",
    date: "2025-12-05",
    status: "pending",
    category: "Career",
    priority: "high",
    mentor: "Rev. Williams",
    prayedBy: [],
    notes: "Needs extra support this week",
    studentId: "STU-2025-001",
    grade: "10th Grade",
    school: "Central High School",
    subject: "Mathematics",
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "michael@example.com",
    request:
      "Pray for my relationship with my mentor who has been guiding me through challenges. We had a disagreement recently and I need wisdom to rebuild our connection.",
    date: "2025-12-04",
    status: "fulfilled",
    category: "Relationship",
    priority: "medium",
    mentor: "Pastor Davis",
    prayedBy: ["Rev. Johnson", "Sister Mary"],
    notes: "Mentor relationship is improving",
    studentId: "STU-2025-002",
    grade: "11th Grade",
    school: "Eastside Academy",
    subject: "Science",
  },
  {
    id: 3,
    name: "Emma Rodriguez",
    email: "emma@example.com",
    request:
      "Pray for wisdom in my mentorship decisions and guidance for my future. I have an important meeting with my mentor next week and need clarity on my academic path.",
    date: "2025-12-03",
    status: "in-progress",
    category: "Wisdom",
    priority: "high",
    mentor: "Dr. Thompson",
    prayedBy: ["Rev. Johnson"],
    notes: "Has upcoming important meeting",
    studentId: "STU-2025-003",
    grade: "12th Grade",
    school: "Westfield High",
    subject: "English",
  },
  {
    id: 4,
    name: "James Wilson",
    email: "james@example.com",
    request:
      "Pray for my academic performance. I'm struggling with advanced calculus and need understanding and focus to improve my grades.",
    date: "2025-12-02",
    status: "pending",
    category: "Academic",
    priority: "medium",
    mentor: "Mrs. Garcia",
    prayedBy: [],
    notes: "Tutoring scheduled for next week",
    studentId: "STU-2025-004",
    grade: "11th Grade",
    school: "Riverside Prep",
    subject: "Mathematics",
  },
  {
    id: 5,
    name: "Olivia Parker",
    email: "olivia@example.com",
    request:
      "Pray for my family situation. My parents are going through a difficult time and I need strength to support them while focusing on my studies.",
    date: "2025-12-01",
    status: "fulfilled",
    category: "Family",
    priority: "high",
    mentor: "Rev. Martinez",
    prayedBy: ["Rev. Johnson", "Sister Mary", "Pastor Davis"],
    notes: "Family situation stabilized",
    studentId: "STU-2025-005",
    grade: "10th Grade",
    school: "Central High School",
    subject: "History",
  },
];
